parameters:
  jobsbundle:
    databricks:
      host: 'https://dbc-123.cloud.databricks.com'
      token: 'abcd123456'
      notifications:
        on_failure: []

    templates:
      default:
        name: '{identifier} (%kernel.environment%)'

        new_cluster:
          spark_version: '6.5.x-scala2.11'
          node_type_id: '{node_type}'
        notebook_task:
          notebook_path: '/my-project_{current_branch}/main'

      permissions_default:
        users_names: '%jobsbundle.databricks.notifications.on_failure%'
        permission_level: 'CAN_MANAGE'

    jobs:
      main:
        template: '%jobsbundle.templates.default%'
        values:
          node_type: 'i3.2xlarge'
        permission: '%jobsbundle.templates.permissions_default%'
